---
- name: apt repo
  apt_repository:
    repo: ppa:ondrej/php

- name: install packages
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: latest
  with_items:
    - git
    - mcrypt
    - nginx
    - php7.2-cli
    - php7.2-curl
    - php7.2-fpm
    - php7.2-intl
    - php7.2-json
    - php7.2-common
    - php7.2-gd
    - php7.2-mbstring
    - php7.2-bcmath
    - php7.2-imap
    - php7.2-xml
    - php7.2-zip
    - php7.2-sqlite3
    - sqlite3
    - unzip

- name: ensure php7.2-fpm cgi.fix_pathinfo=0
  lineinfile:
    dest: /etc/php/7.2/fpm/php.ini
    regexp: '^(.*)cgi.fix_pathinfo='
    line: cgi.fix_pathinfo=0
  notify:
    - restart php7.2-fpm
    - restart nginx
